prompt Tworzenie tabeli Osoby...
create table osoby(
 id_osoby number generated by default on null as identity
,imie varchar2(100) not null
,nazwisko varchar2(100) not null
,pesel varchar2(11)
,constraint osoby_pk PRIMARY KEY (id_osoby)
,constraint pesel_check CHECK(length(pesel)=11)
);

prompt Tworzenie tabeli Agenci...
create table agenci(
 nr_agenta number generated always as identity
,nazwa varchar2(100) not null
,constraint agenci_pk PRIMARY KEY (nr_agenta)
);

prompt Tworzenie tabeli Polisy...
create table polisy(
 nr_polisy number generated by default on null as identity
,nr_agenta number not null
,data_od date	not null
,data_do date	not null
,skladka number	not null
,suma_ubezpieczenia number not null
,constraint polisy_pk PRIMARY KEY (nr_polisy)
,constraint agenci_polisy_fk FOREIGN KEY (nr_agenta) REFERENCES agenci (nr_agenta) ON DELETE CASCADE
)
partition by range (data_od) 
(
 partition do1990 values less than (DATE '1990-01-01')
,partition do1995 values less than (DATE '1995-01-01')
,partition do2000 values less than (DATE '2000-01-01')
,partition do2005 values less than (DATE '2005-01-01')
,partition do2010 values less than (DATE '2010-01-01')
,partition do2015 values less than (DATE '2015-01-01')
,partition do2020 values less than (DATE '2020-01-01')
,partition reszta values less than (maxvalue)
);

PROMPT Tworzenie tabeli Rola...
create table rola(
 "ID_ROLI"          number generated always as identity
,"NAZWA"            varchar2(50) not null
,constraint rola_pk primary key ("ID_ROLI")
,constraint nazwa_check CHECK (NAZWA in('ubezpieczaj¹cy','ubezpieczony') ) 
);

PROMPT Tworzenie tabeli Kontrahenci...
create table kontrahenci(
 nr_polisy	number	not NULL
,id_osoby	number	not null
,id_roli	number 	not null
,constraint polisy_kontrah_fk FOREIGN KEY (nr_polisy) REFERENCES polisy (nr_polisy) ON DELETE CASCADE
,constraint rola_kontrah_fk FOREIGN KEY (id_roli) REFERENCES rola(id_roli) ON DELETE CASCADE
,constraint osoby_kontrah_fk FOREIGN KEY (id_osoby) REFERENCES osoby (id_osoby) ON DELETE CASCADE
);

PROMPT Tworzenie Indexu Kontrahenci_Idx_Unique...
CREATE UNIQUE INDEX Kontrahenci_Idx_Unique on kontrahenci(
nr_polisy, --nr_polisy jest zawsze sprawdzany
case 
	WHEN id_roli=2 THEN id_osoby -- id_osoby jest dodawane do sprawdzania gdy id_roli=2 (ubezpieczony)
end
);

prompt Tworzenie tabeli Szkody_Status...
create table szkody_status(
 id_status number generated by default on null as identity
,nazwa varchar2(20) not null
,constraint szkody_status_pk PRIMARY KEY (id_status)
,constraint nazwa_chk CHECK (nazwa IN ('zg³oszona','rozpatrywana','odrzucona','wyp³acona')) 
);

prompt Tworzenie tabeli Szkody...
create table szkody(
 id_szkody number generated by default on null as identity
,nr_polisy number not null
,id_osoby number not null
,data_zajscia date not null
,data_zgloszenia date not null
,id_status number not null
,wartosc_wyplaty number default 0 not null
,constraint szkody_pk PRIMARY KEY (id_szkody)
,constraint szkody_polisy_fk FOREIGN KEY (nr_polisy) REFERENCES polisy(nr_polisy) ON DELETE CASCADE
,constraint szkody_osoby_fk FOREIGN KEY (id_osoby) REFERENCES osoby(id_osoby) ON DELETE CASCADE
,constraint status_szk_szkody_fk FOREIGN KEY (id_status) REFERENCES szkody_status (id_status) ON DELETE CASCADE
,constraint szkody_daty_chk CHECK (data_zgloszenia>=data_zajscia)
,constraint wartosc_wyplaty_check CHECK (id_status between 1 and 3 AND wartosc_wyplaty = 0 OR id_status = 4 and wartosc_wyplaty>=0)
)
partition by range (data_zajscia) 
(
 partition do1990 values less than (DATE '1990-01-01')
,partition do1995 values less than (DATE '1995-01-01')
,partition do2000 values less than (DATE '2000-01-01')
,partition do2005 values less than (DATE '2005-01-01')
,partition do2010 values less than (DATE '2010-01-01')
,partition do2015 values less than (DATE '2015-01-01')
,partition do2020 values less than (DATE '2020-01-01')
,partition reszta values less than (maxvalue));

PROMPT Tworzenie tabeli info_log...
create table info_log (
 "ID"               number generated always as identity
,"EVENT"            varchar2(50)
,"DATA"             date not null
,"TIME"             varchar2(20)
,"USER"             varchar2(100) not null
,"DB_NAME"          varchar2(100) not null
,"SESSION_ID"       number	
,"IP_ADDRESS"       varchar2(100) not null
,"NETWORK_PROTOCOL" varchar2(100) not null
,constraint info_log_pk primary key ("ID")
);


create table stat_info (
 statystyki varchar2(50)
,wiersze_polisy number
,wiersze_kontrahenci number
,wiersze_szkody number
);
